### ISSUE TITLE
Other test results

### ISSUE THREAD

**Issue by Armand1** [ben18785/Selection_simulations#7]
When we fit log series, lognormal and power law distributions to the WF simulations with _beta_ ranging between 0 and  -1 (NFD), and choose the best fitting distribution by AIC, we find that at relatively weak selection (beta < -0.5), the best fit is log series, but at stronger levels of selection that it becomes lognormal. This is great: exactly what we expect. It makes our discussion of this test of neutrality more reasonable: we can reject neutrality using this test --- but not at weaker levels of selection. Which is fine.

[WF_SADs.pdf](https://github.com/ben18785/Selection_simulations/files/2710344/WF_SADs.pdf)

Here the best fitting distribution is shown (yellow is log series; red is log normal)

**Comment by Armand1** [comment]
When we fit log series, lognormal and power law distributions to the WF simulations with S ranging between 0 and NFD -1, and choose the best fitting distribution by AIC, we find that at relatively weak selection (beta < -0.5, the best fit is log series, but at stronger levels of selection that it becomes lognormal. This is great: exactly what we expect.  It makes our discussion of this test of neutrality more reasonable: we _can_ reject neutrality using this test --- but not at weaker levels of selection.  Which is fine. 

[WF_SADs.pdf](https://github.com/ben18785/Selection_simulations/files/2710325/WF_SADs.pdf)

**Comment by ben18785** [comment]
Great. Selection with beta ~ 0.5 is still reasonably strong though (looking at time series plots), in that it’s easy to discern by eye. In the real series that we have, the effect of selection is generally less obvious; again diluting the worth of power law tests...
